### PR TITLE
Add some nonbinary role names

### PR DESCRIPTION
**Pull request by RojjaCebolla**
not committed to or confident about all of these, but i feel like a few of the M or F role names would feel wrong if they got defaulted to by an NB character for lack of an NB entry

### CODE REVIEW

**Comment by NullCGT** [comment]
"Pirate Nobility" sounds more like a group name than an individual name to me.

**Comment by RojjaCebolla** [comment]
Adjust anything you like on this branch! 😃 
Pirate Patrician? Blue-blood? Just plain noble?

**Comment by copperwater** [comment]
> "Pirate Nobility" sounds more like a group name than an individual name to me.

"Pirate Noble", of course. Or "Pirate Leader" for parallelization with gnome/dwarf/elf/vampire lord/lady/leader.

Also a number of these don't really sound explicitly male to me in the existing neuter form - "Conqueror", "Chieftain", "Reconnoiterer", "Plunderer" could all be used for a person of arbitrary gender. If the concern is that the same term is used for male and neuter and female gets a different one, then just drop the female-specific name.

**Comment by NullCGT** [comment]
I'm with copperwater on this one. I specifically avoided adding a number of NB role names, since the "male" names are already considered gender neutral. I also spent time researching whether there were gender neutral forms of names like "Chevalier," and did not change them after coming to the conclusion that there were none.

I think that more distinction for nonbinary role names is good, but I'm not sure that adding "-ist" as a suffix is the best way to address it.

**Comment by RojjaCebolla** [comment]
Updated! In the likely event they're not all desirable, take it as a list of ideas rather than a commit. 😁

**Pull request merged**
