### PR TITLE
Orctown

### PR DESCRIPTION
**Pull request by RojjaCebolla**
i wanna use XNH's orctown, and then add an orcish kitchen to it

### CODE REVIEW

**Comment by RojjaCebolla** [comment]
https://travis-ci.org/github/RojjaCebolla/SpliceHack/builds/748537326

**Comment by copperwater** [comment]
Not related to this PR really but FYI, a kitchen themed room is coming soon to xNetHack.

**Comment by NullCGT** [comment]
I'm interested in pulling this in, but what are the changes to non-orctown levels for?

**Comment by copperwater** [comment]
Looks like part of that first (xNetHack) commit, which wasn't orctown specific. Note that it does change distributions - math.random(4,8) is uniform over that range, not the same as d(4,2) - but I'm pretty sure these *used* to be in dice notation in 3.6.

**Comment by RojjaCebolla** [comment]
i thought it'd be weird if only Orctown used the more readable d(y,z) notation and the other minetowns used the math.random function

i can ditch that commit if ya want

**Comment by RojjaCebolla** [comment]
is it possible to directly equip the orc with an apron and a pot when it is spawned?  can the orc be named "Chef" while otherwise being a normal hill orc, or do i need to create a specific NPC like Thoth Amon?

**Comment by copperwater** [comment]
Not possible with current 3.7 sp_lev.c code. The proper solution would be to enhance sp_lev.c so that a monster could be spawned with specific inventory items, similar to how specific chest contents are handled. Creating a new entry in monst.c just for this flavor patch is overkill in my opinion (and likely to be bug prone because the new species would need to be added to several scattered places).

**Comment by NullCGT** [comment]
I agree with copperwater that creating a new entry in monst.c would be overkill, and that the proper solution would be to enhance sp_lev.c.

**Comment by copperwater** [comment]
Thinking about it, the orc should be able to be named Chef with the current level parser, but can't be given specific items. You could theoretically hack a way around this by making him an orc species that doesn't otherwise appear in orctown (say, the plain "orc"), and augmenting makemon.c with a check that says "if 'orc' species AND in Minetown AND in the minetn-1 variant AND g.in_mklev is true, give it these items."

But adding hardcoding like that is inflexible, tightly coupled, and capable of breaking things at some later point (the general direction in 3.7 has been to *remove* hardcodings in C as the level parser has been enhanced), so it'd be really up to NullCGT if a system this convoluted is desirable or not.

You could also instead spawn an apron and pot underneath it hoping it picks them up. I'd opt for a more orcish name than "Chef" though.

**Comment by RojjaCebolla** [comment]
Well, i'm pretty jazzed to say that it compiled without warnings or errors. However, it doesn't seem to create the kitchen. Rats! 
image

**Pull request closed without merging**
