### PR TITLE
Xnethack fixes (WIP) (other contributors welcome)

### PR DESCRIPTION
**Pull request by RojjaCebolla**
Just pulling some stuff from XNH that seems sound and unlikely to be controversial.  I'll ping @ NullCGT when i'm done grabbing things.

NullCGT or other Splicehack/Slicehack contributors are welcome to add stuff to this!  I think you do so by submitting a PR at https://github.com/RojjaCebolla/SpliceHack/tree/xnethackFixes, but maybe there's an easier way to do it right here in this PR.

### CODE REVIEW

**Comment by RojjaCebolla** [comment]
These commits look quite fun:

https://github.com/copperwater/xNetHack/commit/3d00320b4cba24c981d885fe7a5107babe42a60b#diff-91666d1e44fa38d35dde57f1b77d0487
https://github.com/copperwater/xNetHack/commit/f201b8e4ad1b6a7fef7752c68a1e2ee869037765#diff-91666d1e44fa38d35dde57f1b77d0487
https://github.com/copperwater/xNetHack/commit/4f024dd32363401e7653950dd486f3774c68253e#diff-91666d1e44fa38d35dde57f1b77d0487
https://github.com/copperwater/xNetHack/commit/e84fcd5ea986515c37d3645292a956ad4cbfc2b4#diff-91666d1e44fa38d35dde57f1b77d0487
https://github.com/copperwater/xNetHack/commit/fd4891c62c68a10e5ef1494c72b4b3993d2f0c62#diff-91666d1e44fa38d35dde57f1b77d0487
https://github.com/copperwater/xNetHack/commit/2581ae2b1a7e3647b2e7d4b1b87f2147468dcbf5#diff-91666d1e44fa38d35dde57f1b77d0487

**Comment by RojjaCebolla** [comment]
This seems potentially controversial, but also the commit message is very convincing about the benefits to be gained from this route:  https://github.com/copperwater/xNetHack/commit/b7379f92c6622b87f67e52a17e2dbfe6e2c1f994

**Comment by RojjaCebolla** [comment]
Fixed the build https://travis-ci.org/github/RojjaCebolla/SpliceHack/builds/705495989?utm_source=github_status&utm_medium=notification

**Comment by RojjaCebolla** [comment]
i'm done with this for now, feel free to cherry-pick, squash, merge, interrogate, whatever @NullCGT 😁

**Comment by NullCGT** [comment]
Here are my takes:

> Martial arts always gets its skill bonuses added.

There's actually a comprehensive fix for this in 3.7 which I'm planning on using. I'm very excited to add it,  since I think we can all agree that the martial arts bug should be fixed.

> Rubbing a magic lamp always releases a djinni.

I'm on the fence, but I think I want to add this. It removes some minor annoyance and potentially opens up new strategies.

> Martial arts users never have to deal with a clumsy kick.

This has bothered me for years. Adding.

> Pets won't attack other pets, even if there's a grudge.

Absolutely want to add that one. I wonder if it could be improved by having some sort of indicator that the pets dislike each other (e.g. "The dog snaps at the cat!")

> Replace Medusa level titan.

Personally, I like the Medusa level titan. It can be difficult, but it's almost never enough to outright end a run. The gremlin in that level, however...

> Hallucination negates all incoming gaze attacks.

I love this. Takes an existing mechanic and makes it so much more interesting.

> Identify a wand when it prints an unambiguous message when engraving.

Potentially controversial, but I like it. I should ask aosdict what his thoughts are on doing the same thing with rings and sinks.

> Confused scroll of identify gives enlightenment.

I'm not a big fan of this one, but I'm not sure why I'm not a big fan of it. I have to think about it some more.

Thank you for the PR! :D

**Comment by copperwater** [comment]
> > Identify a wand when it prints an unambiguous message when engraving.

> Potentially controversial, but I like it. I should ask aosdict what his thoughts are on doing the same thing with rings and sinks.

I've been meaning to get to this one. :+1: 

> > Confused scroll of identify gives enlightenment.

> I'm not a big fan of this one, but I'm not sure why I'm not a big fan of it. I have to think about it some more.

My reason for adding it was basically twofold: 1) confused identify is useless as-is, and 2) adding more sources of enlightenment is a good thing because it helps with deducing object identities.

**Comment by RojjaCebolla** [comment]
when you say "Adding", do you mean you'll cherry pick the commits you like yourself? or just that you dig it, and that i should update the PR and drop the commit that you weren't into?

**Comment by NullCGT** [comment]
@RojjaCebolla Sorry about that, I was unclear. As soon as you update the PR, I'll pull it in!

**Comment by RojjaCebolla** [comment]
Replaced with https://github.com/NullCGT/SpliceHack/pull/102

**Pull request closed without merging**
