### PR TITLE
New cmd: #wizclear (^c), does blessed annihilation

### PR DESCRIPTION
**Pull request by RojjaCebolla**

### CODE REVIEW

**Comment by RojjaCebolla** [comment]
I'm gonna commit these because:

1. they make what i'm currently doing (testing other features) faster
2. shouldn't impact gameplay at all for non-devs
3. i've been using "git stash" to carry these changes around with me as i work on other branches, and the commands are workin great. just getting tired of git stash and git pop ;)

happy to revert or modify these changes as needed!

**Comment by copperwater** [comment]
Mapping a command to ctrl-c interferes with running the game in gdb, as ctrl-c is a common way to halt the program and enter the debugger prompt. The set of people who use wizard mode but aren't nethack devs is likely small.

**Comment by RojjaCebolla** [comment]
thanks! i was surprised ctrl-c didn't already do something, now i know why.

**Comment by copperwater** [comment]
It doesn't *break* anything to make a command be ctrl-c, but it will inevitably cause both scenarios:
* You're running splice in a debugger to test something, decide you want to sweep some monsters - agh! Have to continue at the debugger prompt and possibly redraw the screen after.
* (probably more common) You're running splice in a debugger and decide you want to inspect the state of the monster/map/player/whatever, so you send a SIGINT by hitting ctrl-c... works fine, but after you continue, agh! Get me out of this annihilation prompt that comes up after every. single. interrupt.

Better just not to have it.

**Comment by RojjaCebolla** [comment]
there's no annihilation prompt, but thanks for the detailed scenario 😁

**Pull request merged**
